# .github/workflows/create_pdf.yml
name: Create PDF
on:
  push:
    paths:
      - '**.md'
      - '.github/workflows/create_pdf.yml'

jobs:
  lint:
    name: Create PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: '18.20.4'
      - run: |
          sudo apt install fonts-noto
          node -v
          npm install
          npx md-to-pdf ./test.md
      - uses: actions/upload-artifact@v4
        with:
          name: create-pdf
          path: ./test.pdf
